version = 1

; --- Global settings applied to all models ---
; These values serve as a baseline. You can override them per-model if needed.
[*]
; Offload all layers to the GPU (if you have limited VRAM, lower this number)
n-gpu-layers = 99
; 256k by default
ctx-size = 262144
; Use the model's built-in Jinja chat template (recommended for modern models)
jinja = true
; Enable Flash Attention if supported by your GPU/backend for better performance
flash-attn = true
; Quantize KV cache to 8bit
cache-type-k = q8_0
cache-type-v = q8_0
; Vision set to CPU
no-mmproj-offload = true
; Limit image cap
image-max-tokens = 1024
; Batch sizes
ubatch-size = 512
batch-size = 2048

; --- Model-specific presets ---

; Preset for Occamy 1.0 (Multimodal)
[Accio-Lab/occamy-1.0-GGUF]
model = /models/Accio-Lab/occamy-1.0-GGUF/occamy-1.0-IQ3_M.gguf
mmproj = /models/Accio-Lab/occamy-1.0-GGUF/mmproj-occamy-1.0-F16.gguf
ctx-size = 262144

; Preset for Gemma4-26B (Multimodal)
[HauhauCS/Gemma4-26B-A4B-Uncensored-HauhauCS-Balanced]
model = /models/HauhauCS/Gemma4-26B-A4B-Uncensored-HauhauCS-Balanced/Gemma4-26B-A4B-Uncensored-HauhauCS-Balanced-IQ4_XS.gguf
mmproj = /models/HauhauCS/Gemma4-26B-A4B-Uncensored-HauhauCS-Balanced/mmproj-Gemma4-26B-A4B-Uncensored-HauhauCS-Balanced-f16.gguf
ctx-size = 262144

; Preset for Gemma-4-E4B (Multimodal)
[HauhauCS/Gemma-4-E4B-Uncensored-HauhauCS-Aggressive]
model = /models/HauhauCS/Gemma-4-E4B-Uncensored-HauhauCS-Aggressive/Gemma-4-E4B-Uncensored-HauhauCS-Aggressive-IQ4_XS.gguf
mmproj = /models/HauhauCS/Gemma-4-E4B-Uncensored-HauhauCS-Aggressive/mmproj-Gemma-4-E4B-Uncensored-HauhauCS-Aggressive-f16.gguf
ctx-size = 262144

; Preset for Qwen3.8-27B (Multimodal)
[ISTA-DASLab/Qwen3.8-27B-GSQ-RCO-GGUF]
model = /models/ISTA-DASLab/Qwen3.8-27B-GSQ-RCO-GGUF/Qwen3.8-27B-GSQ-RCO-IQ3_S-mtp.gguf
mmproj = /models/ISTA-DASLab/Qwen3.8-27B-GSQ-RCO-GGUF/mmproj-Qwen3.8-27B-BF16.gguf
ctx-size = 196608
