name: comfyui

services:
  comfyui:
    image: yanwk/comfyui-boot:cu130-slim-v2-20260814
    container_name: comfyui
    network_mode: "host"
    # ports:
    #   - "8188:8188"
    environment:
      - CLI_ARGS=
    volumes:
      - ./.cache:/root/.cache
      - ./.config:/root/.config
      - ./.local:/root/.local
      - ./workflows:/root/ComfyUI/user/default/workflows

      - ${HOME}/Pictures/comfyui/input:/root/ComfyUI/input
      - ${HOME}/Pictures/comfyui/output:/root/ComfyUI/output

      - ${COMFYUI_ROOT}/user-profile:/root/ComfyUI/user
      - ${COMFYUI_ROOT}/user-scripts:/root/user-scripts
      - ${COMFYUI_ROOT}/custom_nodes:/root/ComfyUI/custom_nodes
      - ${COMFYUI_ROOT}/models:/root/ComfyUI/models
      - ${COMFYUI_ROOT}/hf-hub:/root/.cache/huggingface/hub
      - ${COMFYUI_ROOT}/torch-hub:/root/.cache/torch/hub
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0', '1']
              capabilities: [gpu]
    restart: "no"

